[package]
name = "ssh-notifier"
description = "在有人ssh连接到主机时发送提醒和欢迎语"
version = "0.3.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
dirs = "6.0.0"
env_logger = "0.11.8"
indoc = "2.0.7"
kdl = "6.5.0"
log = "0.4.29"
